### ISSUE TITLE
Initial checklist

### ISSUE THREAD

**Issue by HerbCaudill** [HerbCaudill/bcn-flix#1]
- [x] Get jest working
- [x] Serve movies via Apollo Server
- [x] Wire up front end with Apollo Client
- [x] Wire up hidden movies state
- [ ] Filter by time
- [ ] Filter by rating
